# Generated by Django 4.0.4 on 2022-05-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photo_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gallery.category'),
        ),
        migrations.AddField(
            model_name='photos',
            name='photo_location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.location'),
        ),
    ]
