# Generated by Django 4.0.4 on 2022-05-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_photos_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='photo',
            field=models.ImageField(default='image.jpg', upload_to='pictures/'),
        ),
    ]
