# Generated by Django 4.0.4 on 2022-05-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photos_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_name',
            new_name='category_name',
        ),
    ]
